import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Curated sidebar for the SENATRAN mock docs. Explicit labels and ordering per
 * DEVAI ADR-DOCS-IA Decision 5 (no fully-autogenerated trees).
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      items: [{ type: 'doc', id: 'index', label: 'Overview' }],
    },
  ],
};

export default sidebars;
